"""Client report bundle generation from canonical findings."""

from __future__ import annotations

import html
import json
from collections import Counter
from pathlib import Path
from typing import Any

from adaf_attack.core.findings import Finding, findings_from_session, write_findings


def _load_mappings() -> dict[str, Any]:
    from importlib.resources import files

    import yaml

    root = files("adaf_attack.mappings")
    mitre = yaml.safe_load(root.joinpath("mitre_attack.yaml").read_text(encoding="utf-8"))
    nis2 = yaml.safe_load(root.joinpath("nis2_article_21.yaml").read_text(encoding="utf-8"))
    return {"mitre": mitre or {}, "nis2": nis2 or {}}


def enrich_findings(findings: list[Finding]) -> list[dict[str, Any]]:
    mappings = _load_mappings()
    mitre = mappings["mitre"].get("techniques", {})
    nis2 = mappings["nis2"].get("finding_mappings", {})
    return [
        {
            **finding.document(),
            "technique_names": [mitre.get(item, item) for item in finding.attack_techniques],
            "nis2_themes": nis2.get(finding.id, []),
        }
        for finding in findings
    ]


def _style() -> str:
    return """body{font-family:Arial,sans-serif;color:#172033;margin:0;background:#f6f8fb}main{max-width:960px;margin:auto;background:white;padding:52px}h1{font-size:34px;color:#14213d}h2{margin-top:34px;color:#1d4e89;border-bottom:2px solid #d7e5f5;padding-bottom:8px}h3{margin-bottom:4px}.meta{color:#526273}.card{border-left:5px solid #d64545;padding:12px 18px;margin:14px 0;background:#fff5f5}.high{border-color:#e8871e}.medium{border-color:#e0bb00}.low{border-color:#3c9d5d}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #dfe5ec;text-align:left;vertical-align:top}th{background:#eef4fb}.footer{margin-top:46px;font-size:12px;color:#667085}@media print{body{background:white}main{padding:0}.card{break-inside:avoid}}"""


def _finding_html(item: dict[str, Any], technical: bool) -> str:
    evidence = ", ".join(f"{e['artifact']} {e['pointer']}" for e in item["evidence"])
    technical_text = f"<p><b>Evidence:</b> {html.escape(evidence)}</p><p><b>MITRE:</b> {html.escape(', '.join(item['attack_techniques']))}</p>" if technical else ""
    return f"<section class='card {html.escape(item['severity'])}'><h3>{html.escape(item['title'])}</h3><p><b>{html.escape(item['severity'].upper())}</b> - {html.escape(item['impact'])}</p><p><b>Recommended action:</b> {html.escape(item['remediation'])}</p>{technical_text}</section>"


def _document(title: str, subtitle: str, body: str) -> str:
    return f"<!doctype html><html><head><meta charset='utf-8'><title>{html.escape(title)}</title><style>{_style()}</style></head><body><main><h1>{html.escape(title)}</h1><p class='meta'>{html.escape(subtitle)}</p>{body}<p class='footer'>Generated by ADAF-ATTACK from redacted, hash-manifested session evidence. Compliance mappings are assessment aids, not certifications.</p></main></body></html>"


def _pdf(pdf_path: Path, title: str, findings: list[dict[str, Any]], kind: str) -> bool:
    """Generate a dependable simple PDF when reportlab is installed."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
    except ImportError:
        return False
    styles = getSampleStyleSheet()
    parts = [Paragraph(title, styles["Title"]), Spacer(1, 18)]
    for item in findings:
        parts.extend(
            [
                Paragraph(f"{item['severity'].upper()}: {item['title']}", styles["Heading2"]),
                Paragraph(item["impact"], styles["BodyText"]),
            ]
        )
        if kind == "technical":
            evidence = ", ".join(
                f"{entry['artifact']} {entry['pointer']}" for entry in item["evidence"]
            )
            parts.append(Paragraph(f"Evidence: {evidence}", styles["BodyText"]))
            parts.append(
                Paragraph(
                    f"MITRE ATT&CK: {', '.join(item['attack_techniques']) or 'Not mapped'}",
                    styles["BodyText"],
                )
            )
        if kind == "remediation":
            parts.append(Paragraph("Suggested owner: Identity / platform owner", styles["BodyText"]))
        parts.extend([Paragraph(f"Recommended action: {item['remediation']}", styles["BodyText"]), Spacer(1, 10)])
    SimpleDocTemplate(str(pdf_path), pagesize=letter, title=title).build(parts)
    return True


def generate_report_bundle(session: Path, *, engagement_id: str = "unassigned") -> dict[str, str | int]:
    findings = findings_from_session(session)
    write_findings(session, findings)
    rich = enrich_findings(findings)
    output = session / "reports"
    output.mkdir(exist_ok=True)
    counts = Counter(item["severity"] for item in rich)
    try:
        cleanup = json.loads((session / "cleanup.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        cleanup = []
    cleanup_counts = Counter(item.get("status", "pending") for item in cleanup)
    summary = "".join(f"<tr><td>{html.escape(severity.title())}</td><td>{count}</td></tr>" for severity, count in sorted(counts.items())) or "<tr><td>None</td><td>0</td></tr>"
    executive_body = f"<h2>Engagement overview</h2><p>Engagement: <b>{html.escape(engagement_id)}</b>. The assessment identified <b>{len(rich)}</b> evidence-backed findings.</p><h2>Risk posture</h2><table><tr><th>Severity</th><th>Findings</th></tr>{summary}</table><h2>Cleanup status</h2><p>Pending: {cleanup_counts['pending']} | Completed: {cleanup_counts['completed']} | Failed: {cleanup_counts['failed']}</p><h2>Priority decisions</h2>{''.join(_finding_html(item, False) for item in rich[:10])}"
    technical_body = "<h2>Evidence-backed findings</h2>" + "".join(_finding_html(item, True) for item in rich) + "<h2>Scope limitation</h2><p>Results represent only the authorized target scope and collected evidence.</p>"
    remediation_rows = "".join(f"<tr><td>{html.escape(item['severity'])}</td><td>{html.escape(item['title'])}</td><td>{html.escape(item['remediation'])}</td><td>Identity / platform owner</td></tr>" for item in rich)
    remediation_body = f"<h2>Prioritized remediation backlog</h2><table><tr><th>Priority</th><th>Finding</th><th>Action</th><th>Suggested owner</th></tr>{remediation_rows}</table><h2>Verification</h2><p>Re-run the affected collection capability after the approved remediation change.</p>"
    documents = {"executive": executive_body, "technical": technical_body, "remediation": remediation_body}
    paths: dict[str, str | int] = {"finding_count": len(rich)}
    for kind, body in documents.items():
        title = f"ADAF-ATTACK {kind.title()} Report"
        html_path = output / f"{kind}-report.html"
        html_path.write_text(_document(title, f"Engagement {engagement_id}", body), encoding="utf-8")
        paths[f"{kind}_html"] = str(html_path)
        pdf_path = output / f"{kind}-report.pdf"
        if _pdf(pdf_path, title, rich, kind):
            paths[f"{kind}_pdf"] = str(pdf_path)
    (output / "report-manifest.json").write_text(json.dumps(paths, indent=2) + "\n", encoding="utf-8")
    return paths
