"""Capability modules.

Importing this package registers all available capabilities.
"""

from adaf_attack.capabilities import (
    acl_enum,
    acl_primitives,
    acl_write,
    ad_cve_scan,
    adcs_enum,
    adcs_esc,
    adcs_policy_probe,
    asrep_roast,
    asreq_userhunt,
    attack_paths,
    bloodhound_export,
    campaign_analysis,
    campaign_run,
    capability_catalog,
    cert_request,
    coerce,
    coercion_map,
    credential_free,
    computer_takeover,
    credential_inventory,
    credential_ops,
    dcsync,
    delegation_ops,
    dmsa_ops,
    dns_ops,
    esc_chain,
    gmsa_laps_enum,
    gpo_abuse,
    gpo_link,
    gpo_sysvol,
    gpp_cpassword,
    identity_bridge,
    impacket_exec,
    joined_workflows,
    kerberoast,
    laps_read,
    ldap_enum,
    maq_ops,
    next_actions,
    ntlm_relay,
    password_spray,
    pkinit_auth,
    rbcd,
    relay_ops,
    report,
    rodc_delegation,
    rollback,
    s4u_abuse,
    sccm_ops,
    secretsdump_local,
    shadow_creds,
    sysvol_hunt,
    template_mod,
    ticket_forge,
    ticket_lifecycle,
    trusts_enum,
    unpac_the_hash,
    workflow_wrappers,
)
from adaf_attack.core.engineering import load_plugins

load_plugins()
