"""Capability modules.

Importing this package registers all available capabilities.
"""

from adaf_attack.capabilities import (  # noqa: F401
    acl_enum,
    acl_write,
    ad_cve_scan,
    adcs_enum,
    adcs_policy_probe,
    asrep_roast,
    asreq_userhunt,
    attack_paths,
    bloodhound_export,
    campaign_analysis,
    cert_request,
    coerce,
    coercion_map,
    dcsync,
    esc_chain,
    gmsa_laps_enum,
    gpo_abuse,
    gpo_link,
    gpo_sysvol,
    gpp_cpassword,
    identity_bridge,
    impacket_exec,
    kerberoast,
    laps_read,
    ldap_enum,
    next_actions,
    ntlm_relay,
    password_spray,
    pkinit_auth,
    rbcd,
    report,
    rodc_delegation,
    s4u_abuse,
    secretsdump_local,
    shadow_creds,
    sysvol_hunt,
    template_mod,
    ticket_forge,
    ticket_lifecycle,
    trusts_enum,
    unpac_the_hash,
    workflow_wrappers,
)
